version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
permissions:
  - object: /
    pattern: "*scripts*"
    owner: ec2-user
    group: ec2-user
    mode: 744
    type:
      - directory
hooks:
  AfterInstall:
    - location: scripts/down.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: root