version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  ApplicationStop:
    - location: scripts/down.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/build.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/start.sh
      timeout: 300
      runas: root