version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
permissions:
  - object: /
    pattern: "*.sh"
    owner: ec2-user
    group: ec2-user
    mode: 744
    type:
      - file
hooks:
  ValidateService:
    - location: scripts/build.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/start.sh
      timeout: 300
      runas: root